name: Flutter Multi-OS Build

on:
  push:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-build: --no-analytics  # Отключаем аналитику

      - name: Build Windows
        shell: bash  # Явно указываем bash для кросс-платформенных команд
        run: |
          flutter pub get
          flutter pub upgrade  # Обновляем зависимости
          flutter build windows --release
          mkdir -p finished_program/windows  # -p для игнорирования существования
          cp -r build/windows/runner/Release/* finished_program/windows/

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: finished_program
          path: finished_program/windows/
          retention-days: 5

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-build: --no-analytics

      - name: Build Linux
        run: |
          flutter pub get
          flutter pub upgrade
          flutter build linux --release
          mkdir -p finished_program/linux
          cp -r build/linux/arm64/release/bundle/* finished_program/linux/

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: finished_program
          path: finished_program/linux/
          retention-days: 5

  build-web-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-build: --no-analytics

      - name: Build Web
        run: |
          flutter pub get
          flutter pub upgrade
          flutter build web --release
          mkdir -p finished_program/web
          cp -r build/web/* finished_program/web/

      - name: Build Android
        run: |
          flutter build apk --release
          mkdir -p finished_program/android
          cp build/app/outputs/flutter-apk/app-release.apk finished_program/android/

      - name: Upload Web/Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: finished_program
          path: |
            finished_program/web/
            finished_program/android/
          retention-days: 5

  commit-artifacts:
    needs: [build-windows, build-linux, build-web-android]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Разрешение на запись в репозиторий

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: finished_program
          path: finished_program

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add finished_program/
          git commit -m "Update build artifacts [skip ci]"  # Пропускаем триггер CI
          git push