name: Flutter Build Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # Кэширование для ускорения
      - name: Cache Flutter artifacts
        uses: actions/cache@v3
        with:
          path: |
            /opt/hostedtoolcache/flutter
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

      # Сборка для Windows
      - name: Build Windows
        run: |
          flutter build windows --release
          mkdir -p finished_program/windows
          cp -r build/windows/runner/Release/* finished_program/windows/

      # Сборка для Linux
      - name: Build Linux
        run: |
          flutter build linux --release
          mkdir -p finished_program/linux
          cp -r build/linux/arm64/release/bundle/* finished_program/linux/

      # Сборка Web
      - name: Build Web
        run: |
          flutter build web --release
          mkdir -p finished_program/web
          cp -r build/web/* finished_program/web/

      # Сборка Android (без подписи)
      - name: Build Android
        run: |
          flutter build apk --release
          mkdir -p finished_program/android
          cp build/app/outputs/flutter-apk/app-release.apk finished_program/android/

      # Артефакты вместо коммита в репозиторий
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: finished_program
          path: finished_program/
          retention-days: 5