name: Flutter Web/Android Build

on:
  push:
    branches: [main]

jobs:
  # build-windows:  # Закомментировано по запросу
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     # ... остальные шаги Windows ...

  # build-linux:  # Закомментировано по запросу
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     # ... остальные шаги Linux ...

  build-web-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-build: --no-analytics

      - name: Build Web
        run: |
          flutter pub get
          flutter build web --release
          mkdir -p finished_program/web
          cp -r build/web/* finished_program/web/

      - name: Build Android
        run: |
          flutter build apk --release
          mkdir -p finished_program/android
          cp build/app/outputs/flutter-apk/app-release.apk finished_program/android/

      - name: Upload Web/Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: finished_program
          path: |
            finished_program/web/
            finished_program/android/
          retention-days: 5

  commit-artifacts:
    needs: [build-web-android]  # Только зависимость от актуального job
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: finished_program
          path: finished_program

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add finished_program/
          git commit -m "Update web/android builds [skip ci]"
          git push