commit-artifacts:
  needs: [build-web-android]
  runs-on: ubuntu-latest
  permissions:
    contents: write

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Явное указание токена

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: finished_program
        path: finished_program

    - name: Commit and push
      run: |
        # Копируем артефакты в корень репозитория
        cp -r finished_program/* .
        
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add finished_program/
        
        # Проверяем изменения перед коммитом
        if git diff-index --quiet HEAD; then
          echo "Нет изменений для коммита"
        else
          git commit -m "Update web/android builds [skip ci]"
          git push origin HEAD:${{ github.ref }}
        fi