name: Flutter Build & Release

on:
  push:
    branches:
      - main  # Запускать при пуше в main

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Create Output Folder
        run: mkdir -p finished_program/android

      - name: Move APK
        run: mv build/app/outputs/flutter-apk/app-release.apk finished_program/android/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: finished_program/android/

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --no-codesign

      - name: Create Output Folder
        run: mkdir -p finished_program/ios

      - name: Move iOS Build
        run: mv build/ios/iphoneos finished_program/ios/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: finished_program/ios/

  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web

      - name: Create Output Folder
        run: mkdir -p finished_program/web

      - name: Move Web Build
        run: mv build/web finished_program/web/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: finished_program/web/

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows EXE
        run: flutter build windows

      - name: Create Output Folder
        run: mkdir -p finished_program/windows

      - name: Move Windows Build
        run: mv build/windows/runner/Release finished_program/windows/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: finished_program/windows/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build macOS App
        run: flutter build macos

      - name: Create Output Folder
        run: mkdir -p finished_program/macos

      - name: Move macOS Build
        run: mv build/macos/Build/Products/Release finished_program/macos/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-app
          path: finished_program/macos/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Linux
        run: flutter build linux

      - name: Create Output Folder
        run: mkdir -p finished_program/linux

      - name: Move Linux Build
        run: mv build/linux/x64/release/bundle finished_program/linux/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-app
          path: finished_program/linux/
